// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/higuruchi/participant-app/internal/externalinterface/server"
)

// Injectors from wire.go:

func InitializeServerz() server.Server {
	serverServer := server.NewServer()
	return serverServer
}
