// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/higuruchi/participant-app/internal/externalinterface/database"
	"github.com/higuruchi/participant-app/internal/externalinterface/server"
	"github.com/higuruchi/participant-app/internal/interfaceadapter/controller"
	"github.com/higuruchi/participant-app/internal/interfaceadapter/repository"
	"github.com/higuruchi/participant-app/internal/usecase"
)

// Injectors from wire.go:

func InitializeServer() (server.Server, func()) {
	databaseHandler, cleanup := database.NewDBHandler()
	participantsRepository := repository.NewParticipantsRepository(databaseHandler)
	participantsUsecase := usecase.NewParticipantsUsecase(participantsRepository)
	participantsController := controller.NewParticipantsController(participantsUsecase)
	serverServer := server.NewServer(participantsController)
	return serverServer, func() {
		cleanup()
	}
}
