// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/higuruchi/participant-app/internal/config"
	"github.com/higuruchi/participant-app/internal/externalinterface/database"
	"github.com/higuruchi/participant-app/internal/externalinterface/server"
	"github.com/higuruchi/participant-app/internal/interfaceadapter/controller"
	"github.com/higuruchi/participant-app/internal/interfaceadapter/repository"
	"github.com/higuruchi/participant-app/internal/usecase"
)

// Injectors from wire.go:

func InitializeServer(configConfig *config.Config) (server.Server, func()) {
	databaseHandler, cleanup := database.NewDBHandler(configConfig)
	participantsRepository := repository.NewParticipantsRepository(databaseHandler)
	participantsUsecase := usecase.NewParticipantsUsecase(participantsRepository)
	participantsController := controller.NewParticipantsController(participantsUsecase)
	userRepository := repository.NewUserRepository(databaseHandler)
	userUsecase := usecase.NewUserUsecase(userRepository)
	userController := controller.NewUserController(userUsecase)
	serverServer := server.NewServer(participantsController, userController, configConfig)
	return serverServer, func() {
		cleanup()
	}
}
